pipeline {
    agent any // This specifies that the pipeline can run on any available agent.
    stages {
        stage('Test') {
            steps {
                sh 'node --version'
            }
        }
    }
}
