pipeline {
    agent any
    stages {
        stage('Test') {
            steps {
                // Use 'bat' for Windows commands
                bat 'node --version'
            }
        }
    }
}
